"""Add triage fields to incident

Revision ID: 075c2c752db0
Revises: 6794ae63a022
Create Date: 2026-01-05 21:53:04.582904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075c2c752db0'
down_revision: Union[str, Sequence[str], None] = '6794ae63a022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_incidents', sa.Column('triage_suggested_severity', sa.String(), nullable=True))
    op.add_column('ai_incidents', sa.Column('triage_suggested_owner_role', sa.String(), nullable=True))
    op.add_column('ai_incidents', sa.Column('triage_suggested_root_cause_category', sa.String(), nullable=True))
    op.add_column('ai_incidents', sa.Column('triage_suggestion_reason', sa.String(), nullable=True))
    op.add_column(
        'ai_incidents',
        sa.Column(
            'triage_status',
            sa.String(),
            nullable=False,
            server_default='SUGGESTED',
        ),
    )
    op.add_column('ai_incidents', sa.Column('triage_confirmed_by', sa.String(), nullable=True))
    op.add_column('ai_incidents', sa.Column('triage_confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('ai_incidents', sa.Column('triage_override_reason', sa.String(), nullable=True))
    op.alter_column('ai_incidents', 'triage_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_incidents', 'triage_override_reason')
    op.drop_column('ai_incidents', 'triage_confirmed_at')
    op.drop_column('ai_incidents', 'triage_confirmed_by')
    op.drop_column('ai_incidents', 'triage_status')
    op.drop_column('ai_incidents', 'triage_suggestion_reason')
    op.drop_column('ai_incidents', 'triage_suggested_root_cause_category')
    op.drop_column('ai_incidents', 'triage_suggested_owner_role')
    op.drop_column('ai_incidents', 'triage_suggested_severity')
    # ### end Alembic commands ###
