"""add corrective_change_request_id to ai_incident

Revision ID: 1cf08eff089d
Revises: 78abb74daf3b
Create Date: 2026-01-02 02:07:51.058834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf08eff089d'
down_revision: Union[str, Sequence[str], None] = '78abb74daf3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_incidents', sa.Column('corrective_change_request_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'ai_incidents', 'change_requests', ['corrective_change_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_incidents', type_='foreignkey')
    op.drop_column('ai_incidents', 'corrective_change_request_id')
    # ### end Alembic commands ###
