"""add prompt_template and prompt_version

Revision ID: 2aee58a912b2
Revises: ede64652c7f1
Create Date: 2026-01-01 18:51:57.031394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2aee58a912b2'
down_revision: Union[str, Sequence[str], None] = 'ede64652c7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    prompt_status_enum = postgresql.ENUM("DRAFT", "SUBMITTED", "ACTIVE", "RETIRED", name="promptstatus")
    prompt_status_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('prompt_versions', sa.Column('prompt_template_id', sa.UUID(as_uuid=False), nullable=False))
    op.add_column('prompt_versions', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('prompt_versions', sa.Column('status', prompt_status_enum, nullable=False))
    op.add_column('prompt_versions', sa.Column('parameters_schema', sa.JSON(), nullable=True))
    op.add_column('prompt_versions', sa.Column('content_hash', sa.String(), nullable=False))
    op.add_column('prompt_versions', sa.Column('diff_from_prev', sa.Text(), nullable=True))
    op.add_column('prompt_versions', sa.Column('change_request_id', sa.UUID(as_uuid=False), nullable=True))
    op.alter_column('prompt_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'prompt_versions', 'change_requests', ['change_request_id'], ['id'])
    op.create_foreign_key(None, 'prompt_versions', 'prompt_templates', ['prompt_template_id'], ['id'])
    op.drop_column('prompt_versions', 'purpose')
    op.drop_column('prompt_versions', 'ai_system_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    prompt_status_enum = postgresql.ENUM("DRAFT", "SUBMITTED", "ACTIVE", "RETIRED", name="promptstatus")
    op.add_column('prompt_versions', sa.Column('ai_system_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('prompt_versions', sa.Column('purpose', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'prompt_versions', type_='foreignkey')
    op.drop_constraint(None, 'prompt_versions', type_='foreignkey')
    op.alter_column('prompt_versions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('prompt_versions', 'change_request_id')
    op.drop_column('prompt_versions', 'diff_from_prev')
    op.drop_column('prompt_versions', 'content_hash')
    op.drop_column('prompt_versions', 'parameters_schema')
    op.drop_column('prompt_versions', 'status')
    op.drop_column('prompt_versions', 'version')
    op.drop_column('prompt_versions', 'prompt_template_id')
    op.drop_table('prompt_templates')
    prompt_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
