"""add change_request table

Revision ID: 59645d8173ea
Revises: d38ba6cc0554
Create Date: 2025-12-31 22:38:42.947603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59645d8173ea'
down_revision: Union[str, Sequence[str], None] = 'd38ba6cc0554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    change_type_enum = postgresql.ENUM("model", "prompt", "rag_source", "config", name="changetype")
    change_status_enum = postgresql.ENUM(
        "draft",
        "submitted",
        "approved",
        "implemented",
        "rejected",
        name="changestatus",
    )
    change_type_enum.create(op.get_bind(), checkfirst=True)
    change_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('change_requests', sa.Column('change_type', change_type_enum, nullable=False))
    op.add_column('change_requests', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('change_requests', sa.Column('business_justification', sa.Text(), nullable=False))
    op.add_column('change_requests', sa.Column('impact_assessment', sa.Text(), nullable=False))
    op.add_column('change_requests', sa.Column('rollback_plan', sa.Text(), nullable=False))
    op.add_column('change_requests', sa.Column('requested_by', sa.String(), nullable=False))
    op.add_column('change_requests', sa.Column('approved_by', sa.String(), nullable=True))
    op.add_column('change_requests', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.alter_column('change_requests', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=change_status_enum,
               existing_nullable=False,
               postgresql_using="status::changestatus")
    op.alter_column('change_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'change_requests', 'ai_systems', ['ai_system_id'], ['id'])
    op.drop_column('change_requests', 'created_by')
    op.drop_column('change_requests', 'purpose')
    op.drop_column('change_requests', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    change_type_enum = postgresql.ENUM("model", "prompt", "rag_source", "config", name="changetype")
    change_status_enum = postgresql.ENUM(
        "draft",
        "submitted",
        "approved",
        "implemented",
        "rejected",
        name="changestatus",
    )
    op.add_column('change_requests', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('change_requests', sa.Column('purpose', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('change_requests', sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'change_requests', type_='foreignkey')
    op.alter_column('change_requests', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('change_requests', 'status',
               existing_type=change_status_enum,
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using="status::varchar")
    op.drop_column('change_requests', 'approved_at')
    op.drop_column('change_requests', 'approved_by')
    op.drop_column('change_requests', 'requested_by')
    op.drop_column('change_requests', 'rollback_plan')
    op.drop_column('change_requests', 'impact_assessment')
    op.drop_column('change_requests', 'business_justification')
    op.drop_column('change_requests', 'description')
    op.drop_column('change_requests', 'change_type')
    change_status_enum.drop(op.get_bind(), checkfirst=True)
    change_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
