"""Add incident assignment fields

Revision ID: 605404c624ce
Revises: 075c2c752db0
Create Date: 2026-01-06 00:05:27.490593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605404c624ce'
down_revision: Union[str, Sequence[str], None] = '075c2c752db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_incidents', sa.Column('assigned_to_role', sa.String(), nullable=True))
    op.add_column('ai_incidents', sa.Column('assigned_to_user', sa.String(), nullable=True))
    op.add_column('ai_incidents', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_incidents', 'assigned_at')
    op.drop_column('ai_incidents', 'assigned_to_user')
    op.drop_column('ai_incidents', 'assigned_to_role')
    # ### end Alembic commands ###
