"""add rca fields to ai_incident

Revision ID: 78abb74daf3b
Revises: efc047bdbb17
Create Date: 2026-01-02 01:28:11.262402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78abb74daf3b'
down_revision: Union[str, Sequence[str], None] = 'efc047bdbb17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    root_cause_enum = sa.Enum(
        "Prompt design",
        "RAG data issue",
        "Model limitation",
        "User misuse",
        "Unknown",
        name="rootcausecategory",
    )
    root_cause_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('ai_incidents', sa.Column('root_cause_category', root_cause_enum, nullable=True))
    op.add_column('ai_incidents', sa.Column('root_cause_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    root_cause_enum = sa.Enum(
        "Prompt design",
        "RAG data issue",
        "Model limitation",
        "User misuse",
        "Unknown",
        name="rootcausecategory",
    )
    op.drop_column('ai_incidents', 'root_cause_description')
    op.drop_column('ai_incidents', 'root_cause_category')
    root_cause_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
