"""add ai_system table

Revision ID: 7abdfaf99713
Revises: e8e03e182b6b
Create Date: 2025-12-31 00:10:04.985917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7abdfaf99713'
down_revision: Union[str, Sequence[str], None] = 'e8e03e182b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    risk_enum = postgresql.ENUM("low", "medium", "high", "critical", name="riskclassification")
    lifecycle_enum = postgresql.ENUM("draft", "active", "deprecated", "retired", name="lifecyclestatus")
    risk_enum.create(op.get_bind(), checkfirst=True)
    lifecycle_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('ai_systems', sa.Column('business_purpose', sa.Text(), nullable=False))
    op.add_column('ai_systems', sa.Column('intended_users', sa.Text(), nullable=False))
    op.add_column('ai_systems', sa.Column('risk_classification', risk_enum, nullable=False))
    op.add_column('ai_systems', sa.Column('owner', sa.String(length=255), nullable=False))
    op.add_column('ai_systems', sa.Column('lifecycle_status', lifecycle_enum, nullable=False))
    op.alter_column('ai_systems', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'ai_systems', ['name'])
    op.drop_column('ai_systems', 'purpose')
    op.drop_column('ai_systems', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    risk_enum = postgresql.ENUM("low", "medium", "high", "critical", name="riskclassification")
    lifecycle_enum = postgresql.ENUM("draft", "active", "deprecated", "retired", name="lifecyclestatus")
    op.add_column('ai_systems', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_systems', sa.Column('purpose', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ai_systems', type_='unique')
    op.alter_column('ai_systems', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('ai_systems', 'lifecycle_status')
    op.drop_column('ai_systems', 'owner')
    op.drop_column('ai_systems', 'risk_classification')
    op.drop_column('ai_systems', 'intended_users')
    op.drop_column('ai_systems', 'business_purpose')
    lifecycle_enum.drop(op.get_bind(), checkfirst=True)
    risk_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
