"""add rag sources and bindings

Revision ID: 9f9fa5f9ae3d
Revises: 2aee58a912b2
Create Date: 2026-01-01 19:05:04.705838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f9fa5f9ae3d'
down_revision: Union[str, Sequence[str], None] = '2aee58a912b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    rag_source_type_enum = sa.Enum(
        "SharePoint",
        "Blob",
        "Web",
        "Confluence",
        "File",
        name="ragsourcetype",
        create_type=False,
    )
    rag_source_status_enum = sa.Enum(
        "DRAFT",
        "SUBMITTED",
        "ACTIVE",
        "RETIRED",
        name="ragsourcestatus",
        create_type=False,
    )
    op.create_table('rag_sources',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_type', rag_source_type_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rag_source_versions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rag_source_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', rag_source_status_enum, nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('ingestion_config', sa.JSON(), nullable=False),
    sa.Column('embedding_config', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('diff_from_prev', sa.Text(), nullable=True),
    sa.Column('change_request_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ),
    sa.ForeignKeyConstraint(['rag_source_id'], ['rag_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_system_prompt_bindings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ai_system_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('prompt_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('active_from', sa.DateTime(), nullable=False),
    sa.Column('active_to', sa.DateTime(), nullable=True),
    sa.Column('activated_by', sa.String(), nullable=False),
    sa.Column('change_request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_system_rag_bindings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ai_system_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rag_source_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('active_from', sa.DateTime(), nullable=False),
    sa.Column('active_to', sa.DateTime(), nullable=True),
    sa.Column('activated_by', sa.String(), nullable=False),
    sa.Column('change_request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ),
    sa.ForeignKeyConstraint(['rag_source_version_id'], ['rag_source_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    rag_source_type_enum = sa.Enum(
        "SharePoint",
        "Blob",
        "Web",
        "Confluence",
        "File",
        name="ragsourcetype",
        create_type=False,
    )
    rag_source_status_enum = sa.Enum(
        "DRAFT",
        "SUBMITTED",
        "ACTIVE",
        "RETIRED",
        name="ragsourcestatus",
        create_type=False,
    )
    op.drop_table('ai_system_rag_bindings')
    op.drop_table('ai_system_prompt_bindings')
    op.drop_table('rag_source_versions')
    op.drop_table('rag_sources')
    # ### end Alembic commands ###
