"""add last_changed_at to ai_systems

Revision ID: b336543ea7db
Revises: 59645d8173ea
Create Date: 2026-01-01 01:20:57.403898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b336543ea7db'
down_revision: Union[str, Sequence[str], None] = '59645d8173ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_systems', sa.Column('last_changed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_systems', 'last_changed_at')
    # ### end Alembic commands ###
