"""add state_hash and lifecycle states

Revision ID: d38ba6cc0554
Revises: 7abdfaf99713
Create Date: 2025-12-31 02:25:59.768449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd38ba6cc0554'
down_revision: Union[str, Sequence[str], None] = '7abdfaf99713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE lifecyclestatus ADD VALUE IF NOT EXISTS 'submitted'")
    op.execute("ALTER TYPE lifecyclestatus ADD VALUE IF NOT EXISTS 'approved'")
    op.add_column('audit_logs', sa.Column('state_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'state_hash')
    # ### end Alembic commands ###
