"""add audit_metadata column

Revision ID: e4548b0ff8da
Revises: 1cf08eff089d
Create Date: 2026-01-02 02:29:27.958109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4548b0ff8da'
down_revision: Union[str, Sequence[str], None] = '1cf08eff089d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('audit_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'audit_metadata')
    # ### end Alembic commands ###
