"""add last_change_request_id to ai_systems

Revision ID: ede64652c7f1
Revises: b336543ea7db
Create Date: 2026-01-01 01:45:22.079381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede64652c7f1'
down_revision: Union[str, Sequence[str], None] = 'b336543ea7db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_systems', sa.Column('last_change_request_id', sa.UUID(as_uuid=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_systems', 'last_change_request_id')
    # ### end Alembic commands ###
