"""add ai_incident table

Revision ID: efc047bdbb17
Revises: 9f9fa5f9ae3d
Create Date: 2026-01-02 00:55:11.679509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc047bdbb17'
down_revision: Union[str, Sequence[str], None] = '9f9fa5f9ae3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_incidents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ai_system_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_type', sa.Enum('HALLUCINATION', 'INCORRECT_OUTPUT', 'POLICY_VIOLATION', 'BIAS', 'UNSAFE_RECOMMENDATION', name='incidenttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='incidentseverity'), nullable=False),
    sa.Column('impact_area', sa.Enum('REGULATORY', 'CUSTOMER', 'PATIENT', 'FINANCIAL', 'REPUTATIONAL', name='impactarea'), nullable=False),
    sa.Column('detected_by', sa.String(), nullable=False),
    sa.Column('detection_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_INVESTIGATION', 'RESOLVED', 'CLOSED', name='incidentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_incidents')
    # ### end Alembic commands ###
